app/models/Students.py
from app import db

#import json
#from flask import Flask, request, flash, url_for, redirect, render_template
#from flask_sqlalchemy import SQLAlchemy

class students(db.Model):
  id = db.Column('student_id', db.Integer, primary_key = True)
  name = db.Column(db.String(100))
  city = db.Column(db.String(50))
  addr = db.Column(db.String(200)) 
  pin = db.Column(db.String(10))

  def __init__(self, name, city, addr, pin):
    self.name = name
    self.city = city
    self.addr = addr
    self.pin = pin

app/__init__.py
import json
from flask import Flask, g, request, flash, url_for, redirect, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_oidc import OpenIDConnect

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'

app.config.update({
    'SECRET_KEY': 'SomethingNotEntirelySecret',
    'TESTING': True,
    'DEBUG': True,
    'OIDC_CLIENT_SECRETS': 'client_secrets.json',
    'OIDC_ID_TOKEN_COOKIE_SECURE': False,
    'OIDC_REQUIRE_VERIFIED_EMAIL': False,
    'OIDC_USER_INFO_ENABLED': True,
    'OIDC_OPENID_REALM': 'dataplatform',
    'OIDC_SCOPES': ['openid', 'email', 'profile'],
    'OIDC_INTROSPECTION_AUTH_METHOD': 'client_secret_post'
})

oidc = OpenIDConnect(app)
db = SQLAlchemy(app)

from app import route

app/routes/db.py
from flask import Blueprint
from app import db
from flask import Flask, g, request, flash, url_for, redirect, render_template
from app.models.Students import students
import json

api_db = Blueprint('api_db', __name__)

@api_db.route("/student")
def show_all():
  print(students.query.all())
  return render_template('show_all.html', students = students.query.all() )

@api_db.route('/student-new', methods = ['GET', 'POST'])
def new():
  if request.method == 'POST':
    print('In Post')
    if not request.form['name'] or not request.form['city'] or not request.form['addr']:
         print('Please enter all the fields')
         flash('Please enter all the fields', 'error')
    else:
      student = students(name=request.form['name'], city=request.form['city'],
                         addr=request.form['addr'], pin=request.form['pin'])
      print('Record was received')
      db.session.add(student)
      db.session.commit()
      print('Record was successfully added')
      flash('Record was successfully added')
      return redirect(url_for('api_db.show_all'))
  return render_template('new.html')
  
@api_db.route('/student/<string:name>', methods=['GET'])
def get_student(name):
  student = students.query.filter_by(name=name).first()
  print(vars(student))
  result = {}
  result['id'] = student.id
  result['name'] = student.name
  result['city'] = student.city
  result['addr'] = student.addr
  result['pin'] = student.pin
  return json.dumps(result)
  
@api_db.route('/student/<string:name>', methods=['DELETE'])
def delete_student(name):
  student = students.query.filter_by(name=name).first()
  result = {}
  result['id'] = student.id
  result['name'] = student.name
  result['city'] = student.city
  result['addr'] = student.addr
  result['pin'] = student.pin
  db.session.delete(student)
  db.session.commit()
  return json.dumps(result)

app/routes/oidc.py
from flask import Blueprint
from app import oidc
from flask import g

api_user = Blueprint('api_user', __name__)

""" Backend for api that verify OIDC access_token """
@api_user.route("/api")
@oidc.accept_token(require_token=True, render_errors=True)
def oidc_token_detail():
  print("oidc-token details")
  user = {}
  user['preferred_username'] = g.oidc_token_info['preferred_username']
  user['name'] = g.oidc_token_info['name']
  user['email'] = g.oidc_token_info['email']
  user['sub'] = g.oidc_token_info['sub']
  user['realm_access'] = g.oidc_token_info['realm_access']
  
  print(g.oidc_token_info['preferred_username'])
  print(g.oidc_token_info['name'])
  print(g.oidc_token_info['email'])
  print(g.oidc_token_info['sub'])
  print(g.oidc_token_info['realm_access'])
  return user


""" Frontend: OIDC User Login/Logout """
@api_user.route('/')
def hello_world():
    if oidc.user_loggedin:
        return ('Hello, %s, <a href="/oidc/private">See private</a> '
                '<a href="/oidc/logout">Log out</a>') % \
            oidc.user_getfield('preferred_username')
    else:
        return 'Welcome anonymous, <a href="/oidc/private">Log in</a>'


@api_user.route('/private')
@oidc.require_login
def hello_me():
    """Example for protected endpoint that extracts private information from the OpenID Connect id_token.
       Uses the accompanied access_token to access a backend service.
    """

    info = oidc.user_getinfo(['preferred_username', 'email', 'sub'])

    username = info.get('preferred_username')
    email = info.get('email')
    user_id = info.get('sub')

    if user_id in oidc.credentials_store:
        try:
            from oauth2client.client import OAuth2Credentials
            access_token = OAuth2Credentials.from_json(oidc.credentials_store[user_id]).access_token
            print('access_token=<%s>' % access_token)
            headers = {'Authorization': 'Bearer %s' % (access_token)}
            # YOLO
            greeting = requests.get('http://localhost:8080/greeting', headers=headers).text
        except:
            print("Could not access greeting-service")
            greeting = "Hello %s" % username
    

    return ("""%s your email is %s and your user_id is %s!
               <ul>
                 <li><a href="/oidc/">Home</a></li>                 
                </ul>""" %
            (greeting, email, user_id))

@api_user.route('/logout')
def logout():
    """Performs local logout by removing the session cookie."""

    oidc.logout()
    return 'Hi, you have been logged out! <a href="/oidc/">Return</a>'

app/templates/new.html
<!DOCTYPE html>
<html>
   <body>
   
      <h3>Students - Flask SQLAlchemy example</h3>
      <hr/>
      
      {%- for category, message in get_flashed_messages(with_categories = true) %}
         <div class = "alert alert-danger">
            {{ message }}
         </div>
      {%- endfor %}
      
      <form action = "{{ request.path }}" method = "post">
         <label for = "name">Name</label><br>
         <input type = "text" name = "name" placeholder = "Name" /><br>
         <label for = "email">City</label><br>
         <input type = "text" name = "city" placeholder = "city" /><br>
         <label for = "addr">addr</label><br>
         <textarea name = "addr" placeholder = "addr"></textarea><br>
         <label for = "PIN">City</label><br>
         <input type = "text" name = "pin" placeholder = "pin" /><br>
         <input type = "submit" value = "Submit" />
      </form>
      
   </body>
</html>

app/templates/show_all.html
<!DOCTYPE html>
<html lang = "en">
   <head></head>
   <body>
      
      <h3>
         <a href = "{{ url_for('api_db.show_all') }}">Comments - Flask 
            SQLAlchemy example</a>
      </h3>
      
      <hr/>
      {%- for message in get_flashed_messages() %}
         {{ message }}
      {%- endfor %}
		
      <h3>Students (<a href = "{{ url_for('api_db.new') }}">Add Student
         </a>)</h3>
      
      <table>
         <thead>
            <tr>
               <th>Name</th>
               <th>City</th>
               <th>Address</th>
               <th>Pin</th>
            </tr>
         </thead>
         
         <tbody>
            {% for student in students %}
               <tr>
                  <td>{{ student.name }}</td>
                  <td>{{ student.city }}</td>
                  <td>{{ student.addr }}</td>
                  <td>{{ student.pin }}</td>
               </tr>
            {% endfor %}
         </tbody>
      </table>
      
   </body>
</html>